# vim:ft=hyprlang #

# Pull default hyprland background into memory:
preload = /home/mark/Pictures/wall0.png

# Set the default hyrpland background as the wallpaper to all monitors:
wallpaper = , /home/mark/Pictures/wall0.png
