return {
  {
    "nvim-treesitter/nvim-treesitter",
    --@type TSConfig
    opts = {
      ensure_installed = {
        "bash",
        "c_sharp",
        "dockerfile",
        "go",
        "gomod",
        "gowork",
        "gosum",
        "html",
        "hyprlang",
        "javascript",
        "json",
        "latex",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "rust",
        "sql",
        "terraform",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "yaml",
        "zig",
      },
    },
  },
}
