#!/usr/bin/env bash

rosewater='0xfff5e0dc'
overlay0='0xff6c7086'

options=(
  style='round'
  width=5.0
  hidpi='on'
  active_color="glow(${rosewater})"
  inactive_color="$overlay0"
)

borders "${options[@]}"
