#!/usr/bin/env bash

CONFIG_DIR="$HOME/.config/sketchybar"

# Build the C helper (started from init.lua with colors)
(cd "$CONFIG_DIR/helper" && make) >/dev/null 2>&1

# Unload macOS volume overlay
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

# Run the Lua configuration
cd "$CONFIG_DIR"
lua init.lua
