#!/usr/bin/env zsh

# ################## #
# SCRIPTING ADDITION #
# ################## #

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# ####### #
# SIGNALS #
# ####### #

yabai -m signal --add event=space_changed action="zsh -c ~/.config/yabai/scripts/clean_empty_spaces.sh"

# ##### #
# RULES #
# ##### #

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(1Password|Bitwarden|Logi Options|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# ############### #
# GLOBAL SETTINGS #
# ############### #

yabai -m config \
  debug_output off \
  external_bar all:45:0 \
  menubar_opacity 1.0 \
  mouse_follows_focus off \
  focus_follows_mouse off \
  display_arrangement_order default \
  window_origin_display default \
  window_placement second_child \
  window_insertion_point focused \
  window_zoom_persist off \
  window_shadow float \
  window_opacity off \
  window_opacity_duration 0.2 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.95 \
  window_animation_duration 0.3 \
  window_animation_easing ease_out_circ \
  insert_feedback_color 0xff9dd274 \
  split_ratio 0.50 \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

# ############## #
# SPACE SETTINGS #
# ############## #

yabai -m config \
  layout bsp \
  split_type auto \
  top_padding 0 \
  bottom_padding 8 \
  left_padding 8 \
  right_padding 8 \
  window_gap 10 \
  auto_balance off
