#!/usr/bin/env sh

# ################## #
# SCRIPTING ADDITION #
# ################## #

# for this to work you must configure sudo such that
# it will be able to run the command without password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# ####### #
# SIGNALS #
# ####### #

yabai -m signal --add event=space_changed action="sh ~/.config/yabai/scripts/clean_empty_spaces.sh"

# ##### #
# RULES #
# ##### #

# Always float:
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Bitwarden$" manage=off
yabai -m rule --add app="^Finder$" manage=off

# ############### #
# GLOBAL SETTINGS #
# ############### #

yabai -m config \
  debug_output off \
  external_bar all:40:0 \
  menubar_opacity 1.0 \
  mouse_follows_focus off \
  focus_follows_mouse off \
  display_arrangement_order default \
  window_origin_display default \
  window_placement second_child \
  window_insertion_point focused \
  window_zoom_persist on \
  window_shadow off \
  window_opacity off \
  window_opacity_duration 0.0 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.90 \
  window_animation_duration 0.0 \
  window_animation_easing ease_out_circ \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

# ############## #
# SPACE SETTINGS #
# ############## #

yabai -m config \
  layout bsp \
  split_type auto \
  top_padding 3 \
  bottom_padding 5 \
  left_padding 5 \
  right_padding 5 \
  window_gap 5 \
  auto_balance off
