#!/usr/bin/env sh

# ####### #
# SIGNALS #
# ####### #

# Configure scripting addition:
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# MacOS native tabs workarounds:

# Ghostty:
yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'

# Finder:
yabai -m signal --add app='^Finder$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Finder$' event=window_destroyed action='yabai -m space --layout bsp'

# ##### #
# RULES #
# ##### #

# Float System Settings:
yabai -m rule --add app="^System Settings$" manage=off
# Float Bitwarden:
yabai -m rule --add app="^Bitwarden$" manage=off

# Flash window on focus change:
yabai -m signal --add label="flash_focus" event="window_focused" action="yabai -m window \$YABAI_WINDOW_ID --opacity 0.1 && sleep $(yabai -m config window_opacity_duration) && yabai -m window \$YABAI_WINDOW_ID --opacity 0.0"

# ############### #
# GLOBAL SETTINGS #
# ############### #

yabai -m config \
  debug_output off \
  external_bar off:40:0 \
  menubar_opacity 1.0 \
  mouse_follows_focus on \
  focus_follows_mouse autofocus \
  display_arrangement_order default \
  window_origin_display default \
  window_placement second_child \
  window_insertion_point focused \
  window_zoom_persist on \
  window_shadow off \
  window_opacity off \
  window_opacity_duration 0.0 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.90 \
  window_animation_duration 0.0 \
  window_animation_easing ease_out_circ \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

# ############## #
# SPACE SETTINGS #
# ############## #

yabai -m config \
  layout bsp \
  split_type auto \
  top_padding 0 \
  bottom_padding 0 \
  left_padding 0 \
  right_padding 0 \
  window_gap 0 \
  auto_balance off

echo "yabai configuration loaded.."
